Convert GOstatsForUnsupportedOrganisms.Rnw to GOstatsForUnsupportedOrganisms.Rmd
Bioconductor/GOstats pull request #4
Opened 2023-05-29 17:56 UTC by sonali8434

@Bioconductor/sweave2rmd @jwokaty I have created a pull request for conversion of GOstatsForUnsupportedOrganisms.Rnw to GOstatsForUnsupportedOrganisms.Rmd. I am going to review my pull request first then I will ask you for the final review.

2023-05-29 18:00 UTC, sonali8434 commented
- [x] the `.Rmd` file knits to `HTML`
- [x] `R CMD build` runs without errors or timeouts
- [x] the tarball from `R CMD build` contains the `HTML` (check with the
  following by substituting the package name and vignette name `tar ztf
  package_name.tar.gz | grep 'doc/vignette_name'`)
- [x] the `.Rnw` file has been removed
- In the `DESCRIPTION` file
  - [x] `BiocStyle` and `knitr` are listed in `Suggests`
  - [x] the line `VignetteBuilder: knitr` exists
  - [x] any added lines use the same spacing and indents as the existing document
- If agreed with the Maintainer
  - [x] the contributor is in the author list in the `DESCRIPTION` file*.
  - [x] the contributor is in the author list in the vignette's YAML*.
- If this pull request involves converting from separate `Author` and  `Maintainer`
  lines to the `Authors@R` vector, please ensure that
  - [x] the `Authors@R` vector includes the maintainer as specified with `role='cre'`.
  - [x] the `Maintainer` line is completely removed.
- [x] `HTML` document is representative of the `PDF` in content and
  in general the presentation
- [x] Where the contributor was not able to preserve the content and presentation
  of the `PDF` is noted as a comment in the pull request
- [x] the R Markdown file is representative of the Sweave document and follows
  best practices, such as replacing links to Bioconductor packages with calls
  to BiocStyle's `Biocpkg()`
- [x] Only files necessary for the conversion are included in the pull request.
- [x] Long lines have been broken up and reformatted, you can achieve this by
  selecting the text in your script and then clicking on `Code > Reflow Comment`
  in R Studio.
- [x] Code blocks are surrounded by a blank line, and there are no blank lines
  before the start or after the end of the code within the code block. 

* Refer to the contribution guide for acceptable formats

2023-06-01 09:27 UTC, sonali8434 commented on vignettes/GOstatsForUnsupportedOrganisms.Rmd
>  available.dbschemas()
Here we find some differences in the output of available.dbschemas() function  like for example we have "WORM_DB" near [31] in original pdf but we have "WORM_DB"  near [28] in the html file I don't think this is any problem but pointing out as a difference from original pdf

2023-06-01 10:19 UTC, sonali8434 commented
Hello @jwokaty  I have completed the review process of this vignette and make sure that R CMD contains html now I think it is ready for your review please review this vignette and let me know is any more modifications are required. I have added toc if you want I will remove it and also I have left one review for your notice I don't think that is any problem but this is just a small difference from original pdf we may ignore that I think.

2023-06-02 04:20 UTC, jwokaty requested changes
Great work here. Just a few small improvements then we can merge.

2023-06-02 04:20 UTC, jwokaty commented on vignettes/GOstatsForUnsupportedOrganisms.Rmd
> +[GOstatsHyperG.html](https://bioconductor.org/packages/devel/bioc/vignettes/GOstats/inst/doc/GOstatsHyperG.html)
Generally, we want to avoid hardcoding the path to a specific branch. I recommend using a relative URL. I think we can also remove the '.html' since it's a link now.

2023-06-02 04:20 UTC, jwokaty commented on vignettes/GOstatsForUnsupportedOrganisms.Rmd
> +available.dbschemas() method from `r Biocpkg("AnnotationForge")`.
Let's mark `available.dbschemas()` as a function with backticks.

2023-06-02 04:20 UTC, jwokaty commented on DESCRIPTION
> +                comment="Converted GOvis and GOstatsForUnsupportedOrganisms vignette from Sweave to R Markdown / HTML."),
Add an `s` to vignette. In the future, if you've worked on multiple vignettes, you can write `Converted vignettes from Sweave to R Markdown / HTML.` to keep it short.

2023-06-02 17:46 UTC, sonali8434 commented
I have made the requested changes @jwokaty please review the changes and let me know if any more modifications are required.

2023-06-05 18:19 UTC, jwokaty approved these changes
Thanks for your hard work :)

2023-06-05 18:21 UTC, merged